package tui

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/charmbracelet/lipgloss"
	"github.com/sendbird/ccx/internal/session"
)

// updateGolden returns true if golden files should be regenerated.
func updateGolden() bool {
	return os.Getenv("UPDATE_GOLDEN") != ""
}

// goldenPath returns the path to a golden file.
func goldenPath(name string) string {
	return filepath.Join("testdata", name+".golden")
}

// assertGolden compares rendered output against a golden file.
// Run with UPDATE_GOLDEN=1 to regenerate.
func assertGolden(t *testing.T, name, got string) {
	t.Helper()
	path := goldenPath(name)

	if updateGolden() {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("updated golden file: %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing golden file %s (run with UPDATE_GOLDEN=1): %v", path, err)
	}
	if got != string(want) {
		// Show diff context
		gotLines := strings.Split(got, "\n")
		wantLines := strings.Split(string(want), "\n")
		maxLines := max(len(gotLines), len(wantLines))
		for i := range min(maxLines, 50) {
			g, w := "", ""
			if i < len(gotLines) {
				g = gotLines[i]
			}
			if i < len(wantLines) {
				w = wantLines[i]
			}
			if g != w {
				t.Errorf("line %d diff:\n  got:  %q\n  want: %q", i+1, g, w)
			}
		}
		if maxLines > 50 {
			t.Errorf("... and %d more lines", maxLines-50)
		}
	}
}

// stripANSIForGolden removes ANSI escape sequences so golden files are readable.
func stripANSIForGolden(s string) string {
	return stripANSI(s)
}

// --- Snapshot Tests ---

func TestRender_TextOnly(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "Hello, can you help me with this?"},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "text_only", stripANSIForGolden(rp.content))
}

func TestRender_SystemTagFolded(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "This is a side question from the user.\nCRITICAL CONSTRAINTS:\n- You have NO tools available"},
			{Type: "text", Text: "What is 2+2?"},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "system_tag_folded", stripANSIForGolden(rp.content))
}

func TestRender_SystemTagUnfolded(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "This is a side question.\nCRITICAL CONSTRAINTS:\n- No tools available"},
			{Type: "text", Text: "What is 2+2?"},
		},
	}
	folds := defaultFolds(entry)
	// Unfold the system_tag
	delete(folds, 0)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "system_tag_unfolded", stripANSIForGolden(rp.content))
}

func TestRender_ToolFolded(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "Let me check that file."},
			{Type: "tool_use", ToolName: "Read", ToolInput: `{"file_path":"/tmp/test.go"}`},
			{Type: "tool_result", Text: "package main\n\nfunc main() {}"},
			{Type: "text", Text: "The file contains a simple main function."},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "tool_folded", stripANSIForGolden(rp.content))
}

func TestRender_ContextSummary(t *testing.T) {
	// Simulates the collapsed side-question context summary
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "context", Text: "(48 background context messages from parent session)"},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "context_summary", stripANSIForGolden(rp.content))
}

func TestRender_MultipleSystemTags(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "local-command-caveat", Text: "Caveat: generated by local commands."},
			{Type: "system_tag", TagName: "command-name", Text: "clear"},
			{Type: "system_tag", TagName: "command-message", Text: "clear"},
			{Type: "system_tag", TagName: "command-args", Text: ""},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "multiple_system_tags", stripANSIForGolden(rp.content))
}

func TestRender_WithBlockCursor(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "Long system reminder content"},
			{Type: "text", Text: "The actual user question"},
		},
	}
	folds := defaultFolds(entry)
	// Block cursor on the system_tag (index 0)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, 0)
	assertGolden(t, "block_cursor_system_tag", stripANSIForGolden(rp.content))
}

func TestRender_BlockStarts(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "First block"},
			{Type: "system_tag", TagName: "task-notification", Text: "task reminder"},
			{Type: "text", Text: "Second block"},
			{Type: "tool_use", ToolName: "Bash", ToolInput: `{"command":"ls"}`},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)

	// blockStarts should have one entry per content block
	if len(rp.blockStarts) != len(entry.Content) {
		t.Errorf("blockStarts length = %d, want %d", len(rp.blockStarts), len(entry.Content))
	}

	// Each subsequent block start should be >= previous
	for i := 1; i < len(rp.blockStarts); i++ {
		if rp.blockStarts[i] < rp.blockStarts[i-1] {
			t.Errorf("blockStarts[%d]=%d < blockStarts[%d]=%d",
				i, rp.blockStarts[i], i-1, rp.blockStarts[i-1])
		}
	}
}

func TestRender_MarkdownTable(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "Here's the summary:\n\n| State | Ctrl+/ does | Esc does |\n|---|---|---|\n| **Panel open** | → Chat mode | (goes to Claude) |\n| **Chat mode** | → Close panel | → Back to focus |\n| **Panel closed** | → Open panel | (goes to Claude) |\n\nNo more conflicts."},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "markdown_table", stripANSIForGolden(rp.content))
}

func TestMarkdownTable_Alignment(t *testing.T) {
	// ASCII table renders as a box-drawing table with a header separator.
	got := renderMarkdownTable([]string{
		"| Name | Age |",
		"|---|---|",
		"| Alice | 30 |",
		"| Bob | 7 |",
	}, 0)
	if !strings.Contains(got, "┌") || !strings.Contains(got, "│") {
		t.Errorf("expected box-drawing chars, got:\n%s", got)
	}
	// All rendered lines share the same display width (aligned columns).
	lines := strings.Split(got, "\n")
	w := lipgloss.Width(lines[0])
	for i, line := range lines {
		if lipgloss.Width(line) != w {
			t.Errorf("line %d display width=%d, want %d: %q", i, lipgloss.Width(line), w, line)
		}
	}
}

func TestMarkdownTable_CJKAlignment(t *testing.T) {
	// The key regression: CJK/emoji/marker cells must align by DISPLAY width, not
	// byte length. Every rendered line must have identical display width.
	got := renderMarkdownTable([]string{
		"| 능력 | ccx | cv |",
		"|---|---|---|",
		"| 프로세스 트리 매핑 | **MarkLiveSessions** | ❌ |",
		"| pane 점프 | `FindPane` | ❌ |",
	}, 0)
	lines := strings.Split(got, "\n")
	if len(lines) < 3 {
		t.Fatalf("expected multi-line table, got:\n%s", got)
	}
	w := lipgloss.Width(lines[0])
	for i, line := range lines {
		if lipgloss.Width(line) != w {
			t.Errorf("CJK line %d display width=%d, want %d: %q", i, lipgloss.Width(line), w, line)
		}
	}
}

func TestMarkdownTable_WidthClampWraps(t *testing.T) {
	// A wide table clamped to a small width must not overflow the budget; cells
	// wrap inside the box instead of shattering the borders.
	got := renderMarkdownTable([]string{
		"| Col A | Col B |",
		"|---|---|",
		"| this is a very long first cell that would overflow | short |",
	}, 40)
	for _, line := range strings.Split(got, "\n") {
		if lipgloss.Width(line) > 40 {
			t.Errorf("line exceeds width budget 40 (got %d): %q", lipgloss.Width(line), line)
		}
	}
	if !strings.Contains(got, "┌") {
		t.Errorf("expected box-drawing table, got:\n%s", got)
	}
}

func TestRenderMarkdownText_TableNotWrapped(t *testing.T) {
	// renderMarkdownText must leave table rows intact (box borders unbroken) while
	// still wrapping surrounding prose.
	text := "Intro line.\n\n| A | B |\n|---|---|\n| x | y |\n\nOutro."
	got := renderMarkdownText(text, 80)
	if !strings.Contains(got, "┌") || !strings.Contains(got, "└") {
		t.Errorf("table borders missing, got:\n%s", got)
	}
	if strings.Contains(got, "| A | B |") {
		t.Errorf("raw markdown table row leaked through unrendered:\n%s", got)
	}
}

func TestRenderMarkdownText_NoTable(t *testing.T) {
	input := "Just regular text\nwith no tables"
	got := renderMarkdownText(input, 80)
	if got != input {
		t.Errorf("non-table text should pass through unchanged, got: %q", got)
	}
}

func TestRenderMarkdownHeading(t *testing.T) {
	cases := []struct {
		line string
		ok   bool
		want string // content after stripping ANSI
	}{
		{"# Title", true, "Title"},
		{"### Sub heading", true, "Sub heading"},
		{"###### h6", true, "h6"},
		{"####### too deep", false, ""},
		{"#no space", false, ""},
		{"not a heading", false, ""},
		{"", false, ""},
	}
	for _, c := range cases {
		got, ok := renderMarkdownHeading(c.line)
		if ok != c.ok {
			t.Errorf("renderMarkdownHeading(%q) ok=%v, want %v", c.line, ok, c.ok)
			continue
		}
		if ok && stripANSI(got) != c.want {
			t.Errorf("renderMarkdownHeading(%q) content=%q, want %q", c.line, stripANSI(got), c.want)
		}
	}
}

func TestApplyInlineMarkdown(t *testing.T) {
	// Markers are stripped; content preserved (styling verified via ANSI strip).
	cases := []struct{ in, want string }{
		{"plain text", "plain text"},
		{"a **bold** word", "a bold word"},
		{"use `code` here", "use code here"},
		{"**b** and `c`", "b and c"},
		{"unclosed **bold", "unclosed **bold"},
	}
	for _, c := range cases {
		if got := stripANSI(applyInlineMarkdown(c.in)); got != c.want {
			t.Errorf("applyInlineMarkdown(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestRender_SeparatorWrappedTextCursorFirstLineOnly(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "[separator]\n\nThis is a long wrapped text block that should keep the cursor marker only on the first rendered line while follow-up wrapped lines are indented instead of repeating the marker."},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 40, folds, nil, 0)
	lines := strings.Split(stripANSIForGolden(rp.content), "\n")
	markerLines := 0
	for _, line := range lines {
		if strings.HasPrefix(line, "› ") || strings.HasPrefix(line, iconFoldOpen+" ") || strings.HasPrefix(line, iconFoldClosed+" ") || strings.HasPrefix(line, iconBlockMarker+" ") {
			markerLines++
		}
	}
	if markerLines != 1 {
		t.Fatalf("expected exactly one marker-prefixed line, got %d\n%s", markerLines, stripANSIForGolden(rp.content))
	}
}

func TestRender_CompactMessage(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 30, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "You must follow these rules"},
			{Type: "text", Text: "What is the weather?"},
		},
	}
	got := renderCompactMessage(entry, 80, 2)
	plain := stripANSI(got)

	// Compact message should show the text content, not the system_tag
	if strings.Contains(plain, "system-reminder") {
		t.Error("compact message should not show system-reminder tag name")
	}
	if !strings.Contains(plain, "What is the weather?") && !strings.Contains(plain, "weather") {
		t.Error("compact message should contain the actual text preview")
	}
}
