package tui

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/sendbird/ccx/internal/session"
)

// updateGolden returns true if golden files should be regenerated.
func updateGolden() bool {
	return os.Getenv("UPDATE_GOLDEN") != ""
}

// goldenPath returns the path to a golden file.
func goldenPath(name string) string {
	return filepath.Join("testdata", name+".golden")
}

// assertGolden compares rendered output against a golden file.
// Run with UPDATE_GOLDEN=1 to regenerate.
func assertGolden(t *testing.T, name, got string) {
	t.Helper()
	path := goldenPath(name)

	if updateGolden() {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("updated golden file: %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("missing golden file %s (run with UPDATE_GOLDEN=1): %v", path, err)
	}
	if got != string(want) {
		// Show diff context
		gotLines := strings.Split(got, "\n")
		wantLines := strings.Split(string(want), "\n")
		maxLines := max(len(gotLines), len(wantLines))
		for i := range min(maxLines, 50) {
			g, w := "", ""
			if i < len(gotLines) {
				g = gotLines[i]
			}
			if i < len(wantLines) {
				w = wantLines[i]
			}
			if g != w {
				t.Errorf("line %d diff:\n  got:  %q\n  want: %q", i+1, g, w)
			}
		}
		if maxLines > 50 {
			t.Errorf("... and %d more lines", maxLines-50)
		}
	}
}

// stripANSIForGolden removes ANSI escape sequences so golden files are readable.
func stripANSIForGolden(s string) string {
	return stripANSI(s)
}

// --- Snapshot Tests ---

func TestRender_TextOnly(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "Hello, can you help me with this?"},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "text_only", stripANSIForGolden(rp.content))
}

func TestRender_SystemTagFolded(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "This is a side question from the user.\nCRITICAL CONSTRAINTS:\n- You have NO tools available"},
			{Type: "text", Text: "What is 2+2?"},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "system_tag_folded", stripANSIForGolden(rp.content))
}

func TestRender_SystemTagUnfolded(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "This is a side question.\nCRITICAL CONSTRAINTS:\n- No tools available"},
			{Type: "text", Text: "What is 2+2?"},
		},
	}
	folds := defaultFolds(entry)
	// Unfold the system_tag
	delete(folds, 0)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "system_tag_unfolded", stripANSIForGolden(rp.content))
}

func TestRender_ToolFolded(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "Let me check that file."},
			{Type: "tool_use", ToolName: "Read", ToolInput: `{"file_path":"/tmp/test.go"}`},
			{Type: "tool_result", Text: "package main\n\nfunc main() {}"},
			{Type: "text", Text: "The file contains a simple main function."},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "tool_folded", stripANSIForGolden(rp.content))
}

func TestRender_ContextSummary(t *testing.T) {
	// Simulates the collapsed side-question context summary
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "context", Text: "(48 background context messages from parent session)"},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "context_summary", stripANSIForGolden(rp.content))
}

func TestRender_MultipleSystemTags(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "local-command-caveat", Text: "Caveat: generated by local commands."},
			{Type: "system_tag", TagName: "command-name", Text: "clear"},
			{Type: "system_tag", TagName: "command-message", Text: "clear"},
			{Type: "system_tag", TagName: "command-args", Text: ""},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "multiple_system_tags", stripANSIForGolden(rp.content))
}

func TestRender_WithBlockCursor(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "Long system reminder content"},
			{Type: "text", Text: "The actual user question"},
		},
	}
	folds := defaultFolds(entry)
	// Block cursor on the system_tag (index 0)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, 0)
	assertGolden(t, "block_cursor_system_tag", stripANSIForGolden(rp.content))
}

func TestRender_BlockStarts(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "First block"},
			{Type: "system_tag", TagName: "task-notification", Text: "task reminder"},
			{Type: "text", Text: "Second block"},
			{Type: "tool_use", ToolName: "Bash", ToolInput: `{"command":"ls"}`},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)

	// blockStarts should have one entry per content block
	if len(rp.blockStarts) != len(entry.Content) {
		t.Errorf("blockStarts length = %d, want %d", len(rp.blockStarts), len(entry.Content))
	}

	// Each subsequent block start should be >= previous
	for i := 1; i < len(rp.blockStarts); i++ {
		if rp.blockStarts[i] < rp.blockStarts[i-1] {
			t.Errorf("blockStarts[%d]=%d < blockStarts[%d]=%d",
				i, rp.blockStarts[i], i-1, rp.blockStarts[i-1])
		}
	}
}

func TestRender_MarkdownTable(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "Here's the summary:\n\n| State | Ctrl+/ does | Esc does |\n|---|---|---|\n| **Panel open** | → Chat mode | (goes to Claude) |\n| **Chat mode** | → Close panel | → Back to focus |\n| **Panel closed** | → Open panel | (goes to Claude) |\n\nNo more conflicts."},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 80, folds, nil, -1)
	assertGolden(t, "markdown_table", stripANSIForGolden(rp.content))
}

func TestFormatMarkdownTables_Alignment(t *testing.T) {
	input := "| Name | Age |\n|---|---|\n| Alice | 30 |\n| Bob | 7 |"
	got := formatMarkdownTables(input)
	lines := strings.Split(got, "\n")
	if len(lines) != 4 {
		t.Fatalf("got %d lines, want 4", len(lines))
	}
	// All lines should have the same length (aligned columns)
	w := len(lines[0])
	for i, line := range lines {
		if len(line) != w {
			t.Errorf("line %d length=%d, want %d: %q", i, len(line), w, line)
		}
	}
	// Header cells should be padded
	if !strings.Contains(lines[0], "| Name  |") {
		t.Errorf("expected padded Name, got: %q", lines[0])
	}
}

func TestFormatMarkdownTables_NoTable(t *testing.T) {
	input := "Just regular text\nwith no tables"
	got := formatMarkdownTables(input)
	if got != input {
		t.Errorf("non-table text should pass through unchanged")
	}
}

func TestRender_SeparatorWrappedTextCursorFirstLineOnly(t *testing.T) {
	entry := session.Entry{
		Role:      "assistant",
		Timestamp: time.Date(2025, 6, 1, 12, 0, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "text", Text: "[separator]\n\nThis is a long wrapped text block that should keep the cursor marker only on the first rendered line while follow-up wrapped lines are indented instead of repeating the marker."},
		},
	}
	folds := defaultFolds(entry)
	rp := renderFullMessageWithCursor(entry, 40, folds, nil, 0)
	lines := strings.Split(stripANSIForGolden(rp.content), "\n")
	markerLines := 0
	for _, line := range lines {
		if strings.HasPrefix(line, "› ") || strings.HasPrefix(line, "▾ ") || strings.HasPrefix(line, "▸ ") || strings.HasPrefix(line, "✦ ") {
			markerLines++
		}
	}
	if markerLines != 1 {
		t.Fatalf("expected exactly one marker-prefixed line, got %d\n%s", markerLines, stripANSIForGolden(rp.content))
	}
}

func TestRender_CompactMessage(t *testing.T) {
	entry := session.Entry{
		Role:      "user",
		Timestamp: time.Date(2025, 6, 1, 12, 30, 0, 0, time.UTC),
		Content: []session.ContentBlock{
			{Type: "system_tag", TagName: "system-reminder", Text: "You must follow these rules"},
			{Type: "text", Text: "What is the weather?"},
		},
	}
	got := renderCompactMessage(entry, 80, 2)
	plain := stripANSI(got)

	// Compact message should show the text content, not the system_tag
	if strings.Contains(plain, "system-reminder") {
		t.Error("compact message should not show system-reminder tag name")
	}
	if !strings.Contains(plain, "What is the weather?") && !strings.Contains(plain, "weather") {
		t.Error("compact message should contain the actual text preview")
	}
}
